/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package view;

import controller.ChiTietHoaDonDAO;
import controller.HoaDonDAO;
import controller.SachDAO;
import java.sql.Timestamp;
import java.text.DecimalFormat;
import java.util.ArrayList;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.QUESTION_MESSAGE;
import javax.swing.table.DefaultTableModel;
import model.ChiTietHoaDon;
import model.HoaDon;
import model.Sach;

/**
 *
 * @author Tran Nhat Sinh
 */
public class SuaHoaDon extends javax.swing.JDialog {

    /**
     * Creates new form ThemSP
     */
    private HoaDonForm owner;
    private DefaultTableModel tblMode1;
    private DefaultTableModel tblMode2;
    DecimalFormat formatter = new DecimalFormat("#,###");
    private int maHoaDon;
    private ArrayList<ChiTietHoaDon> cthd;
    private ArrayList<ChiTietHoaDon> cthdOld = new ArrayList<>();
    private ArrayList<Sach> sachList = new ArrayList<>();
    private HoaDon hd;
    private int updateSum;
    public SuaHoaDon(javax.swing.JInternalFrame parent, javax.swing.JFrame owner, boolean modal) {
        super(owner, modal);
        this.owner = (HoaDonForm) parent;
        hd = this.owner.getHoaDonSelect();
        initComponents();
        tblMode1 = (DefaultTableModel) tblSachHD.getModel();
        tblMode2 = (DefaultTableModel) tblSachMua.getModel();
        setLocationRelativeTo(null);
        
        txtMaHD.setText(createId());
        sachList = SachDAO.getInstance().selectAll();
        cthd = ChiTietHoaDonDAO.getInstance().selectAll(hd.getMaHoaDon());
        cthdOld = ChiTietHoaDonDAO.getInstance().selectAll(hd.getMaHoaDon());
        loadDataToTable(sachList);
        loadDataToTableSachMua();

        txtMaHD.setText(hd.getMaHoaDon() + "");
        txtTenKH.setText(hd.getTenKhachHang());
        textTongTien.setText(formatter.format(hd.getTongTien()) + "đ");
    }

//    private void loadDataToTable(){
////        SachDAO sach = new SachDAO();
////        ArrayList<Sach> listSach = SachDAO.getInstance().selectAll();
//        tblMode1.setRowCount(0);
//        for (Sach i : sachList) {
//
//            tblMode1.addRow(new Object[]{
//                i.getMaSach(), i.getTenSach(), i.getSoLuong(), formatter.format(i.getGiaBan()) + "d"
//            });
//
//        }
    //  }
    private void loadDataToTable(ArrayList<Sach> list) {
        try {
            tblMode1.setRowCount(0);
            for (var i : list) {
                tblMode1.addRow(new Object[]{
                    i.getMaSach(), i.getTenSach(), i.getSoLuong(), formatter.format(i.getGiaBan()) + "d"
                });
            }
        } catch (Exception e) {
        }
    }

    private String createId() {

        ArrayList<HoaDon> listHD = HoaDonDAO.getInstance().selectAll();
        int k = 0;

        for (int i = listHD.size() - 1; i >= 0; i--) {
            k = listHD.get(i).getMaHoaDon();
            break;
        }

        return (k + 1) + "";
    }

    private void initTable() {

    }

    private SuaHoaDon(JFrame jFrame, boolean b) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        txtMaHD = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSachMua = new javax.swing.JTable();
        btnTaoHD = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        textTongTien = new javax.swing.JLabel();
        deleteProduct = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        txtTenKH = new javax.swing.JTextField();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblSachHD = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        addProduct = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        txtSearch = new javax.swing.JTextField();
        btnReset = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));

        jLabel1.setFont(new java.awt.Font("SF Pro Display", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("SỬA HÓA ĐƠN");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(402, 402, 402)
                .addComponent(jLabel1)
                .addContainerGap(544, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 60));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setText("Mã hóa đơn");
        jPanel3.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 60, -1, -1));

        txtMaHD.setEditable(false);
        txtMaHD.setEnabled(false);
        txtMaHD.setFocusable(false);
        jPanel3.add(txtMaHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 50, 270, 36));

        jLabel2.setText("Tên khách hàng");
        jPanel3.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        tblSachMua.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "STT", "Mã Sách", "Tên Sách", "Số lượng", "Thành tiền"
            }
        ));
        jScrollPane1.setViewportView(tblSachMua);
        if (tblSachMua.getColumnModel().getColumnCount() > 0) {
            tblSachMua.getColumnModel().getColumn(0).setMaxWidth(50);
            tblSachMua.getColumnModel().getColumn(3).setMaxWidth(100);
        }

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 190, 520, 230));

        btnTaoHD.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        btnTaoHD.setForeground(new java.awt.Color(255, 255, 255));
        btnTaoHD.setText("Lưu thay đổi");
        btnTaoHD.setBorder(null);
        btnTaoHD.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnTaoHD.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTaoHDActionPerformed(evt);
            }
        });
        jPanel3.add(btnTaoHD, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 530, 123, 37));

        jLabel5.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        jLabel5.setText("Tổng tiền:");
        jPanel3.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 530, 120, 30));

        textTongTien.setFont(new java.awt.Font("SF Pro Display", 1, 18)); // NOI18N
        textTongTien.setForeground(new java.awt.Color(255, 0, 0));
        textTongTien.setText("0đ");
        jPanel3.add(textTongTien, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 530, 160, 30));

        deleteProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_delete_25px_1.png"))); // NOI18N
        deleteProduct.setText("Xoá ");
        deleteProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        deleteProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteProductActionPerformed(evt);
            }
        });
        jPanel3.add(deleteProduct, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 450, 120, 40));

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_edit_25px.png"))); // NOI18N
        jButton1.setText("Sửa số lượng");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel3.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 450, -1, 40));

        txtTenKH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTenKHActionPerformed(evt);
            }
        });
        jPanel3.add(txtTenKH, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 112, 270, 40));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 0, 560, 670));

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));

        tblSachHD.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Mã sách", "Tên sách", "Số lượng", "Đơn giá"
            }
        ));
        jScrollPane2.setViewportView(tblSachHD);

        jLabel4.setText("Số lượng");

        txtSoLuong.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtSoLuong.setText("1");

        addProduct.setBackground(javax.swing.UIManager.getDefaults().getColor("Actions.Green"));
        addProduct.setForeground(new java.awt.Color(255, 255, 255));
        addProduct.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_add_25px_5.png"))); // NOI18N
        addProduct.setText("Thêm");
        addProduct.setBorder(null);
        addProduct.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addProductActionPerformed(evt);
            }
        });

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Tìm kiếm"));

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icon/icons8_reset_25px_1.png"))); // NOI18N
        btnReset.setText("Làm mới");
        btnReset.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 352, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnReset, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(11, 11, 11))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel4)
                .addGap(27, 27, 27)
                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29)
                .addComponent(addProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 363, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(addProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(114, Short.MAX_VALUE))
        );

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 560, 670));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 60, -1, 610));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTaoHDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTaoHDActionPerformed

        if (cthd.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Bạn chưa thêm sách quyen sách nào vào hóa don !", "Cảnh báo", JOptionPane.WARNING_MESSAGE);
        } else if (!txtTenKH.getText().isEmpty()) {
            int check = JOptionPane.showConfirmDialog(this, "Bạn có chắc chắn muốn sua không ?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (check == JOptionPane.YES_OPTION) {
                for (var ct : cthdOld) {
                    SachDAO.getInstance().updateSoLuong(ct.getMaSach(), SachDAO.getInstance().selectById(ct.getMaSach()).getSoLuong() + ct.getSoLuong());
                    System.out.println(ct.getSoLuong());
                }
                for (var ct : cthd) {
                    SachDAO.getInstance().updateSoLuong(ct.getMaSach(), SachDAO.getInstance().selectById(ct.getMaSach()).getSoLuong() - ct.getSoLuong());
                    System.out.println(ct.getSoLuong());
                }
                // Lay thoi gian hien tai
//                long now = System.currentTimeMillis();          
//                Timestamp sqlTimestamp = new Timestamp(now);

                HoaDon hoaDon = new HoaDon(hd.getMaHoaDon(), txtTenKH.getText(), hd.getNgayLap(), updateSum, cthd);
                try {
                    HoaDonDAO.getInstance().update(hoaDon);
                    ChiTietHoaDonDAO.getInstance().delete(cthdOld.get(cthdOld.size() - 1));
                    SachDAO sachDao = SachDAO.getInstance();
                    for (ChiTietHoaDon i : cthd) {
                        ChiTietHoaDonDAO.getInstance().insert(i);
                        System.out.println(i.getMaHoaDon());

                    }
                    JOptionPane.showMessageDialog(this, "Sua hóa đơn thành công!");
//                    int res = JOptionPane.showConfirmDialog(this, "Bạn có muốn xuất file pdf ?","",JOptionPane.YES_NO_OPTION);
//                    if (res == JOptionPane.YES_OPTION) {
//                        WritePDF writepdf = new WritePDF();
//                        writepdf.writePhieuNhap(MaPhieu);
//                    }
                    this.owner.loadDataToTable();
                    this.dispose();
//                    sachList = sachDao.selectAll();
//                    txtSoLuong.setText("1");
//                    loadDataToTable(sachList);
//                    tblMode1.setRowCount(0);
//                    loadDataToTable(sachList);
//                    tblMode2.setRowCount(0);
//                    cthd = new ArrayList<>();
//                    textTongTien.setText("0");
//                    this.maHoaDon = Integer.parseInt(createId());
//                    txtMaHD.setText(createId());
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Đã xảy ra lỗi !");
                }
            }

        } else {
            JOptionPane.showMessageDialog(this, "Bạn chưa nhập tên khách hàng !");
        }
    }//GEN-LAST:event_btnTaoHDActionPerformed

    public int tinhTongTien() {
        int tt = 0;
        for (ChiTietHoaDon i : cthd) {
            tt += i.getThanhTien();
        }
        return tt;
    }
    private void deleteProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteProductActionPerformed
        // TODO add your handling code here:
        int i_row = tblSachMua.getSelectedRow();
        if (i_row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm để xoá khỏi bảng nhập hàng !");
        } else {
            cthd.remove(i_row);
            loadDataToTableSachMua();
            textTongTien.setText(formatter.format(tinhTongTien()) + "đ");
        }
    }//GEN-LAST:event_deleteProductActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        int i_row = tblSachMua.getSelectedRow();
        if (i_row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sản phẩm để xoá sửa số lượng !");
        } else {
            String newSL = JOptionPane.showInputDialog(this, "Nhập số lượng cần thay đổi", "Thay đổi số lượng", QUESTION_MESSAGE);
            if (newSL != null) {
                int soLuong;
                try {
                    soLuong = Integer.parseInt(newSL);
                    if (soLuong > 0) {
                        if (soLuong > findSach(cthd.get(i_row).getMaSach()).getSoLuong()) {
                            JOptionPane.showMessageDialog(this, "Số lượng sách không đủ !");
                        } else {
                            cthd.get(i_row).setSoLuong(soLuong);
                            cthd.get(i_row).setThanhTien(
                                    cthd.get(i_row).getSoLuong()* findSach(cthd.get(i_row).getMaSach()).getGiaBan()
                            );
                            loadDataToTableSachMua();
                            
                        }
                    } else {
                        JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng lớn hơn 0");

                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng ở dạng số nguyên!");
                }
            }
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void addProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addProductActionPerformed
        // TODO add your handling code here:
        int i_row = tblSachHD.getSelectedRow();
        if (i_row == -1) {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn sách de thêm vào hóa don !");
        } else {
            int soluong;
            int maS = 0;
            try {
                soluong = Integer.parseInt(txtSoLuong.getText().trim());
                if (soluong > 0 && soluong < sachList.get(i_row).getSoLuong()) {
                    maS = Integer.parseInt(tblSachHD.getValueAt(i_row, 0).toString());

                    ChiTietHoaDon s1 = findCTHD(maS);
                    if (s1 != null) {
                        s1.setSoLuong(s1.getSoLuong() + soluong);
                        s1.setThanhTien(
                                s1.getSoLuong()*findSach(maS).getGiaBan()
                        );
                    } else {
                        Sach s = SachDAO.getInstance().searchId(maS);
                        ChiTietHoaDon ct = new ChiTietHoaDon(hd.getMaHoaDon(), s.getMaSach(), soluong, s.getGiaBan() * soluong);
                        cthd.add(ct);
                    }
//                    Sach s = SachDAO.getInstance().searchId(maS);
//                        ChiTietHoaDon ct = new ChiTietHoaDon(maHoaDon, s.getMaSach(), soluong, s.getGiaBan()*soluong);
//                        cthd.add(ct);
                    loadDataToTableSachMua();
                    
//                    textTongTien.setText(formatter.format(tinhTongTien()) + "đ");
                } else {
                    JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng > 0 và không lớn hơn số lượng hiện có");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "Vui lòng nhập số lượng ở dạng số nguyên!");
                e.printStackTrace();
            }
        }


    }//GEN-LAST:event_addProductActionPerformed

    public ChiTietHoaDon findCTHD(int maHD) {
        for (ChiTietHoaDon i : cthd) {
            if (maHD == i.getMaSach()) {
                return i;
            }

        }
        return null;
    }

    public Sach findSach(int maS) {
        for (Sach i : sachList) {
            if (maS == i.getMaSach()) {
                return i;
            }
        }
        return null;
    }

    public void loadDataToTableSachMua() {
        int sum = 0;
        try {
            tblMode2.setRowCount(0);

            for (int i = 0; i < cthd.size(); i++) {
                tblMode2.addRow(new Object[]{
                    i + 1, cthd.get(i).getMaSach(), findSach(cthd.get(i).getMaSach()).getTenSach(), cthd.get(i).getSoLuong(), formatter.format(cthd.get(i).getThanhTien()) + "đ"
                });
                sum += cthd.get(i).getThanhTien();
            }
        } catch (Exception e) {
        }
        updateSum = sum;
        textTongTien.setText(formatter.format(sum) + "đ");
    }
    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        String content = txtSearch.getText();
        ArrayList<Sach> result = SachDAO.getInstance().search(content);
        loadDataToTableSearch(result);
    }//GEN-LAST:event_txtSearchKeyReleased

    public void loadDataToTableSearch(ArrayList<Sach> result) {

        tblMode1.setRowCount(0);
        for (Sach i : result) {

            tblMode1.addRow(new Object[]{
                i.getMaSach(), i.getTenSach(), i.getSoLuong(), formatter.format(i.getGiaBan()) + "d"
            });

        }

    }
    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
//        txtSearch.setText("");
//        loadDataToTableProduct(allProduct);
    }//GEN-LAST:event_btnResetActionPerformed

    private void txtTenKHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTenKHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTenKHActionPerformed

    /**
     * @param args the command line arguments
     */
//    public String createIdPC() {
//        ArrayList<MayTinh> mtAll = MayTinhDAO.getInstance().selectAll();
//        ArrayList<MayTinh> pcAll = new ArrayList<MayTinh>();
//        for (MayTinh mayTinh : mtAll) {
//            if (mayTinh.getMaMay().contains("PC")) {
//                pcAll.add(mayTinh);
//            }
//        }
//        int i = pcAll.size();
//        String check ="check";
//        while(check.length()!=0){
//            i++;
//            for (MayTinh mayTinh : pcAll) {
//                if(mayTinh.getMaMay().equals("PC"+i)){
//                    check="";
//                }
//            }
//            if(check.length()==0){
//                check ="check";
//            } else {
//                check = "";
//            }
//        }
//        return "PC" + i;
//    }
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SuaHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SuaHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SuaHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SuaHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                SuaHoaDon dialog = new SuaHoaDon(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addProduct;
    private javax.swing.JButton btnReset;
    private javax.swing.JButton btnTaoHD;
    private javax.swing.JButton deleteProduct;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblSachHD;
    private javax.swing.JTable tblSachMua;
    private javax.swing.JLabel textTongTien;
    private javax.swing.JTextField txtMaHD;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenKH;
    // End of variables declaration//GEN-END:variables
}
